#!/usr/bin/env python3
"""
Geocode the BLCA zone/house list (houses_raw.json) into supabase/seed/seed.sql.

Source data: house numbers per zone come from the "blca bbq aug 2026 delivery"
sheet (just house numbers, no street names). Street-per-zone was read off the
2005 hand-compiled zone map (blca-map-with-zones-2022.png) and is a best-effort
match, not survey-grade -- some zones front more than one physical street
(corner lots), so a fraction of addresses will geocode wrong or fail outright.
That's expected: this script is step (a) from PLAN.md open item 7 ("geocode
with a free geocoder"); step (b) is hand-dragging the mis-placed pins once the
app exists.

Uses Nominatim (OpenStreetMap) per its usage policy: max 1 req/sec, a real
User-Agent, and results are cached to geocode_cache.json so re-runs don't
re-hit the API for addresses already resolved.
"""
import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
RAW = json.loads((HERE / "houses_raw.json").read_text())
CACHE_PATH = HERE / "geocode_cache.json"
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
USER_AGENT = "blca-flier-map-seed/0.1 (contact: axl@liess.tv)"
CAMPAIGN_SLUG = "bbq-aug-2026"
CAMPAIGN_NAME = "BLCA August 2026 BBQ Flier"

cache = json.loads(CACHE_PATH.read_text()) if CACHE_PATH.exists() else {}


def geocode(address: str):
    if address in cache:
        return cache[address]
    params = urllib.parse.urlencode({"q": address, "format": "json", "limit": 1})
    req = urllib.request.Request(f"{NOMINATIM_URL}?{params}", headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            results = json.loads(resp.read())
        result = {"lat": float(results[0]["lat"]), "lng": float(results[0]["lon"])} if results else None
    except Exception as exc:  # noqa: BLE001 - best effort geocoding, failures are expected
        print(f"  ! geocode failed for {address!r}: {exc}")
        result = None
    cache[address] = result
    CACHE_PATH.write_text(json.dumps(cache, indent=2, sort_keys=True))
    time.sleep(1.1)  # Nominatim usage policy: max 1 req/sec
    return result


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main():
    zone_street = RAW["zone_street"]
    city_state_zip = RAW["city_state_zip"]
    houses = RAW["houses"]

    lines = []
    lines.append("-- Generated by supabase/seed/geocode.py -- do not hand-edit, regenerate instead.")
    lines.append("-- Seed data: 22 zones / 357 houses transcribed from the BLCA delivery sheet,")
    lines.append("-- addresses inferred from the zone map (see geocode.py docstring for caveats).")
    lines.append("")
    lines.append("insert into zones (number, name) values")
    zone_rows = [f"  ({z}, {sql_str(zone_street[z])})" for z in sorted(zone_street, key=int)]
    lines.append(",\n".join(zone_rows) + "\non conflict (number) do nothing;")
    lines.append("")

    lines.append("insert into houses (zone_id, address, lat, lng) values")
    house_rows = []
    unresolved = []
    total = sum(len(v) for v in houses.values())
    done = 0
    for zone_num in sorted(houses, key=int):
        street = zone_street[zone_num]
        for house_number in houses[zone_num]:
            done += 1
            address = f"{house_number} {street}, {city_state_zip}"
            print(f"[{done}/{total}] geocoding {address}")
            coords = geocode(address)
            lat_sql = "null" if coords is None else repr(coords["lat"])
            lng_sql = "null" if coords is None else repr(coords["lng"])
            if coords is None:
                unresolved.append(address)
            house_rows.append(
                f"  ((select id from zones where number = {zone_num}), {sql_str(address)}, {lat_sql}, {lng_sql})"
            )
    lines.append(",\n".join(house_rows) + ";")
    lines.append("")

    lines.append(f"insert into campaigns (slug, name, active) values ({sql_str(CAMPAIGN_SLUG)}, {sql_str(CAMPAIGN_NAME)}, true)")
    lines.append("on conflict (slug) do nothing;")
    lines.append("")

    (HERE / "seed.sql").write_text("\n".join(lines) + "\n")

    print(f"\nWrote seed.sql: {total} houses, {len(unresolved)} unresolved (lat/lng null, need hand-placement).")
    if unresolved:
        (HERE / "unresolved_addresses.txt").write_text("\n".join(unresolved) + "\n")
        print("Unresolved addresses listed in unresolved_addresses.txt")


if __name__ == "__main__":
    main()
